mv aa_HW5_break_inElse.out t1.exp
mv aa_HW5_break_inIf.out t2.exp
mv binop_all_1.out t3.exp
mv call_function_in_function_1.out t4.exp
mv CallingFunctionsFromDifferentPlacesBoolFunc.out t5.exp
mv CallingFunctionsFromDifferentPlacesByteFunc.out t6.exp
mv CallingFunctionsFromDifferentPlacesIntFunc.out t7.exp
mv CallingFunctionsFromDifferentPlacesVoidFunc.out t8.exp
mv "check_(Exp)_1.out" t9.exp
mv CheckPrintAndPrinti1.out t10.exp
mv div_zero_1.out t11.exp
mv div_zero_2.out t12.exp
mv div_zero_3.out t13.exp
mv div_zero_4.out t14.exp
mv facebook_div_zero.out t15.exp
mv facebook_if_in_while.out t16.exp
mv facebook_if.out t17.exp
mv facebook_if_test.out t18.exp
mv facebook_recursion.out t19.exp
mv facebook_shitloads_bool_expr.out t20.exp
mv facebook_shitloads_parameters.out t21.exp
mv facebook_simple_func.out t22.exp
mv facebook_simple_test.out t23.exp
mv facebook_tak.out t24.exp
mv facebook_while_test.out t25.exp
mv ifElse_all.out t26.exp
mv notTest.out t27.exp
mv OR_testBoolAsFuncParam.out t28.exp
mv OR_testBoolInAssign.out t29.exp
mv OR_testBoolInAssignWithNot.out t30.exp
mv OR_testBoolInIf3.out t31.exp
mv OR_testBoolInIf.out t32.exp
mv OR_testBoolInIfWithNot.out t33.exp
mv OR_testBoolInVariable1.2.out t34.exp
mv OR_testBoolInVariable1.3.out t35.exp
mv OR_testBoolInVariable1.4.out t36.exp
mv OR_testBoolInVariable2.2.out t37.exp
mv OR_testBoolInVariable2.3.out t38.exp
mv OR_testBoolInVariable2.4.out t39.exp
mv OR_testBoolInVariable2.out t40.exp
mv OR_testBoolInVariable.out t41.exp
mv OR_testBoolInWhile.out t42.exp
mv OR_testBreakAndSwitch.out t43.exp
mv OR_testBreakInnerWhile.out t44.exp
mv OR_testCallArgsOrder.out t45.exp
mv OR_testFunctionCallInControlFlow.out t46.exp
mv OR_testLazyEval.out t47.exp
mv OR_testLonelyIf.out t48.exp
mv OR_testRecursion.out t49.exp
mv OR_testReturnFromControlFlow.out t50.exp
mv OR_testReturnFromIf.out t51.exp
mv OR_testReturnFromWhile.out t52.exp
mv OR_testReturn.out t53.exp
mv OR_testWhile.out t54.exp
mv regular_div_1.out t55.exp
mv Relop_bge.out t56.exp
mv Relop_bgt.out t57.exp
mv Relop_ble.out t58.exp
mv Relop_blt.out t59.exp
mv Relop_bne.out t60.exp
mv Relop_eq.out t61.exp
mv t10.out t62.exp
mv t11.out t63.exp
mv t12.out t64.exp
mv t13.out t65.exp
mv t14.out t66.exp
mv t15.out t67.exp
mv t16.out t68.exp
mv t17.out t69.exp
mv t1.out t70.exp
mv t2.out t71.exp
mv t3.out t72.exp
mv t4.out t73.exp
mv t5-1.out t74.exp
mv t5-2.out t75.exp
mv t5-3.out t76.exp
mv t5.out t77.exp
mv t6.out t78.exp
mv t7.out t79.exp
mv t8.out t80.exp
mv t9.out t81.exp
mv testAssignment.out t82.exp
mv while_call_func_1.out t83.exp
